### ISSUE TITLE
Error in matlab 2016R version 

### ISSUE THREAD

**Issue by Pathithasan** [earthat/DWT-SVD#1]
please help to resolve this error. following error is generated when program moves to embedding. 

Error using ones
Size inputs must be integers.

Error in embedding (line 7)
    gain=P*ones(1,iter);

then i caste iter to integer, following error is generated. 
Error using cat
Dimensions of matrices being concatenated are not consistent.

Error in embedding (line 20)
        temp=cat(1,temp,cD{jj+1});

thanks

**Comment by earthat** [comment]
in it 'iter' is a variable name whose value is assigned from main file. either you didn't pass its value from main. Check out line no 41 in main.m.

 `iter= message_chunks;
gain=3;
[finalwatermrked,U11,V11]=embedding(gain,A,watermark,signalinframe,iter,dwtlevel);`

**Comment by Pathithasan** [comment]
After fixing the issue you mentioned, (the value is  already pass)
iter = int32(iter+0.5); (line 4)
if numel(gain)==1
    gain=P*ones(1,iter); (line 7)
end
for ii=1:iter
    frame=A(cnt:signalinframe*ii);

I receive another issue, 

Error using cat
Dimensions of matrices being concatenated are not consistent.

Error in embedding (line 20)
temp=cat(1,temp,cD{jj+1});
 How can I fix this.

Is possible for me to get any research paper for your project, so that will be great help for me. Also can I get the code for watermark extraction process.

Thanks,
rpathithasan0@gmail.com

**Comment by earthat** [comment]
It seems syntax issue here. You join our chat room on gitter for instant discussion. https://gitter.im/Free-Thesis/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by fkhadi** [comment]
@earthat am getting same error dimensions of matrices being concatenated are not consistent.error in embedding.m(line 19)
temp=cat(1,temp,cD{JJ+1});
And error in main 
[finalwatermarked,U11,V11]=embedding(gain,A,watermark,signalinframe,Iyer,dwtlevel)
