### ISSUE TITLE
Difference result

### ISSUE THREAD

**Issue by nuelsrgh** [earthat/DWT-SVD#3]
I have run your project , but i got different result  between embedding and extraction image 
you can see the result
![embed](https://user-images.githubusercontent.com/38713119/40869622-9ccf70f8-6648-11e8-9fac-8efc886df612.JPG)

![extract](https://user-images.githubusercontent.com/38713119/40869628-b2724dcc-6648-11e8-9dcb-b8b29c24f3db.JPG)

**Comment by nuelsrgh** [comment]
Do you know, how i can solve the problem??

**Comment by earthat** [comment]
This repository don't have any extraction code.

**Comment by nuelsrgh** [comment]
I have bought completely from
http://free-thesis.com/product/audio-watermarking-by-dwt-svd-bfo/

**Comment by earthat** [comment]
ok

**Comment by nuelsrgh** [comment]
So do you know the problem??

**Comment by earthat** [comment]
will check it and update you

**Comment by earthat** [comment]
May I know from which email Id, you bought the code as I don't see yours this one in database.

**Comment by nuelsrgh** [comment]
I got from here
admin@free-thesis.com

**Comment by nuelsrgh** [comment]
Hello when i got the update of the project??

**Comment by vedtra** [comment]
Not working? Wow, iam lucky not buy this product, any body know where i
have to buy the real product?

Pada tanggal Sab, 2 Jun 2018 13.33, nuelsrgh <notifications@github.com>
menulis:

**Comment by nuelsrgh** [comment]
Actually this product had working for embedding process but i know that the
developer must update the project because the project still using the old
matlab code....

and i still waiting for the updated project

Pada tanggal Sel, 5 Jun 2018 15:56, Rohit kamala <notifications@github.com>
menulis:

**Comment by earthat** [comment]
@nuelsrgh I am communicating on your email ID. So closing this thread.

**Comment by nuelsrgh** [comment]
,
